version: "3.3"

services:

  db:
    image: mysql:5.7
    container_name: photo-gallery-mysql
    command: --sort_buffer_size=512K --wait_timeout=800 --max_allowed_packet=512M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  php:
    image: photo-gallery:1.0.0
    container_name: photo-gallery-php
    build:
      context: ./docker/php
      args:
        PROJECT_FILES: ${PROJECT_FILES}
        PHP_VERSION: ${PHP_VERSION}
        USER_ID: ${USER_ID}
    volumes:
      - .:${PROJECT_FILES}
      - ./docker/php/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    networks:
      - app-network

  nginx:
    image: nginx:1.19-alpine
    container_name: photo-gallery-nginx
    depends_on:
      - php
    volumes:
      - .:${PROJECT_FILES}
      - ./docker/nginx/templates:/etc/nginx/templates
    environment:
      NGINX_ROOT: ${PROJECT_FILES}
      NGINX_PORT: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${BASE_URL}`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - app-network

  traefik:
    image: traefik:v2.3
    container_name: photo-gallery-traefik
    depends_on:
      - nginx
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - ${TRAEFIK_PORT}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge